services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5050
    command: npm run dev -- --host
    depends_on:
      - backend
      - ai-agent

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start

  ai-agent:
    build: ./ai-agent
    ports:
      - "5050:5050"
    volumes:
      - ./ai-agent:/app
